### ISSUE TITLE
Initially not working with multiple devices

### ISSUE THREAD

**Issue by redmars27** [joeshaw/wemo-homekit#1]
I have two wemo insights and both of them are detected by wemo-homecontrol but when you go to HomeKit only one of them appears. It seems that you create a new IPTransport per device:

`t, err := hc.NewIPTransport(hcConfig, acc.Accessory)`

I made a test having all the devices added to the same IPTransport and in that case all devices appear properly on HomeKit. When you register the device it appears as a gateway and once connected you have both of the switches.

I don't know if the problem is on the usage of hc (github.com/brutella/hc) or indeed, a problem in hc. Looking on it, it doesn't allow to add new accessories (devices) after an IPTransport is created.

Apart from that all is working like a charm, thanks for it. If you need any help with the code, let me know.

Something I am working on: 
- Force the addition of devices without discovering them, in order to add devices from different networks
- Be able to run wemo-homecontrol in a docker container

**Comment by joeshaw** [comment]
Thanks for the report.  I only have one of these devices, which would explain why it doesn't work with multiples.  I suspect it's a problem with my usage of hc.  I'll take a stab at fixing it, and ask you to test it when it's ready.

**Comment by joeshaw** [comment]
By the way, I'd be happy to take a Dockerfile for this.

**Comment by joeshaw** [comment]
Hmm, not a lot of other hc users do multiple accessories, but some that do (including one by the author) do it similarly to how I'm doing it in this module.  An example, https://github.com/brutella/hklifx/blob/master/hklifxd.go#L128-L162

**Comment by redmars27** [comment]
Well I don't know. I am testing with, "out of the box" configuration on all elements:
- Configure the switches with the mobile wemo app
- Both of them are visible on the app and you can turn them on and off
- Clone your git repo, compile and run
- Both switches are detected by the program
- Open HomeApp on the iPhone
- It detects only one of them as a switch, you can add it to your HomeKit environment

But now that I am writing this, I think the problem can be somewhere else, I will need to test it again when I am back home, but I think that the one detected is not the one added, I mean, it detected one but then when you see which one is in HomeKit is the other one, but I am not 100% sure on this. Looking into the function itself: [https://github.com/brutella/hc/blob/master/ip_transport.go#L52-L68](https://github.com/brutella/hc/blob/master/ip_transport.go#L52-L68) it mentioned that the database can't be the same

`// *Important:* Changing the name of the accessory, or letting multiple`
`// transports store the data inside the same database lead to`
`// unexpected behavior – don't do that.`

Why I am 100% sure is that if instead all calling it once per found device I add them as a list of accessories, both of them appear properly on the homekit app.

`t, err := hc.NewIPTransport(hcConfig, acc1.Accessory,acc2.Accessory)`

Let me check a little bit more and I will let you know.

**Comment by joeshaw** [comment]
Ah! Thanks for the tip.  I think the issue is that I am setting the storage path to be `~/.homecontrol/wemo`, https://github.com/joeshaw/wemo-homecontrol/blob/master/main.go#L461.  I think I was under the assumption that was a base path, and that hc would create a directory per-accessory under that.  This should be a relatively simple fix, I will pass in a new config each time with the serial number tacked onto the end of the directory.

**Comment by redmars27** [comment]
Confirmed, changing the StoragePath in the hcConfig solve the problem.

**Comment by joeshaw** [comment]
One last thing you could check for me: do your accessories have exactly the same name?

**Comment by redmars27** [comment]
no, each one of them has a different name, I have not checked if you can even name them equally on the WemoApp. Anyhow if you want to be sure they are different, you can use the serial number.

**Comment by redmars27** [comment]
Or sorry, were you asking me to test using the same device name for both switches?

**Comment by joeshaw** [comment]
No, I was just curious if they had the same name, for the purpose of the storage directory (since hc's default is to use the accessory name).  But it'll just be simpler to use the serial number.
